language: python
python:
  - "2.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py test home
  - coverage run --source=home manage.py test home
after_success: coveralls