language: python
python:
  - 2.7
  - 3.3
deploy:
  provider: heroku
  api_key:
    secure: "236fc4046bd092d94e17d0ee607b6d95da4994c0"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run manage.py test

after_success:
  coveralls