# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ants_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('group_id', models.IntegerField()),
                ('is_activated', models.IntegerField()),
            ],
        ),
    ]
