# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ants_web', '0003_auto_20161205_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='instructor',
        ),
        migrations.AddField(
            model_name='term',
            name='instructors',
            field=models.ManyToManyField(to='ants_web.Instructor'),
        ),
    ]
