# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ants_web', '0008_auto_20161205_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='day_of_week',
            field=models.IntegerField(),
        ),
    ]
