# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ants_web', '0009_auto_20161215_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='kind',
            field=models.IntegerField(),
        ),
    ]
