# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ants_web', '0010_auto_20161216_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(to='ants_web.Course')),
                ('student', models.ManyToManyField(to='ants_web.Student')),
            ],
        ),
    ]
