# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ants_web', '0011_studentcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='ants_web.Course'),
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
