# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ants_web', '0012_auto_20161216_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('comment', models.CharField(max_length=256)),
                ('student', models.ManyToManyField(to='ants_web.Student')),
                ('term', models.ManyToManyField(to='ants_web.Term')),
            ],
        ),
    ]
