# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 16:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ants_web', '0013_termselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termselection',
            name='student',
        ),
        migrations.AddField(
            model_name='termselection',
            name='student',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='ants_web.Student'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='termselection',
            name='term',
        ),
        migrations.AddField(
            model_name='termselection',
            name='term',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ants_web.Term'),
            preserve_default=False,
        ),
    ]
