# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 21:26
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ants_web', '0014_auto_20161217_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termselection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ants_web.Student'),
        ),
        migrations.AlterField(
            model_name='termselection',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ants_web.Term'),
        ),
    ]
