# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '__first__'),
        ('ants_web', '0015_auto_20161217_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='students.Student'),
        ),
        migrations.AlterField(
            model_name='termselection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
